In [1]:
import pandas as pd

In [5]:
file_path = "datasets/municipal_pfas_sampling.csv"
df = pd.read_csv(file_path)
df.head()

,X,Y,OBJECTID,PWS_ID,PWS_NAME,CITY,DS_RO_SEQ_NO,MCD_CODE,MUNI_TYPE_CODE,SURVEY_TOWNSHIP,SURVEY_RANGE,SURVEY_RANGE_NDIR,SURVEY_SECTION,NUMBER_ENTRY_POINTS,SAMPLE_STATUS,SAMPLE_DATE,SAMPLE_RESULTS
0,655952.9999,267104.1875,4982,26802094,MUKWONAGO WATERWORKS,MUKWONAGO,139193,16.0,0.0,5,18,4,26,3,Sampled,2023/05/25 00:00:00+00,PFAS exceeds hazard index for samples from the...
1,366177.9375,480195.7813,7349,61702630,DOWNSVILLE SANITARY DISTRICT,DOWNSVILLE,145500,NaN,NaN,27,13,2,34,2,NaN,NaN,NaN
2,678005.3124,384163.0312,16588,43604275,KIEL WATERWORKS,KIEL,141745,41.0,2.0,17,21,4,30,4,Sampled,2023/04/18 00:00:00+00,PFAS detected below hazard index in one or mor...
3,431692.8749,394818.0937,17493,63203261,TOWN OF FARMINGTON SANITARY DISTRICT,MINDORO,145907,NaN,NaN,18,6,2,21,2,Sampled,2022/06/15 00:00:00+00,PFAS not detected in any samples from the wate...
4,450354.7813,277497.3125,36022,12201112,MOUNT HOPE WATERWORKS,MOUNT HOPE,135604,38.0,0.0,6,4,2,28,1,NaN,NaN,NaN